import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
import {normalizeQuery,flightUrl} from '../src/model.js';
const code=(await readFile(new URL('../extension/background.js',import.meta.url),'utf8')).replace(/^import .*;\n/,'');
function harness(results){let onConnect,onMessage;const messages=[],created=[],removed=[];
const chrome={runtime:{onConnect:{addListener:fn=>{onConnect=fn;}}},tabs:{onUpdated:{addListener(){},removeListener(){}},get:async()=>({status:'complete'}),create:async opts=>{created.push(opts);return {id:created.length};},remove:async id=>removed.push(id),sendMessage:async(id,m)=>m.type==='ping'?{ready:true}:results[id-1]}};
vm.runInNewContext(code,{chrome,URL,normalizeQuery,flightUrl,setTimeout,clearTimeout});
return {messages,created,removed,connect(url){const port={name:'fare-board',sender:{url},disconnect(){messages.push({type:'disconnected'});},onDisconnect:{addListener(){}},postMessage:m=>messages.push(m),onMessage:{addListener:fn=>{onMessage=fn;}}};onConnect(port);return m=>onMessage(m);}};}
const q=normalizeQuery({flight:'JX201',departure:'2026-10-23',origin:'TPE',destination:'MFM',party:{adults:2,children:[{age:7}]}});
test('background preserves valid family current price with absent-history warning',async()=>{const h=harness([{...q,current:34134,history:[],error:'來源未提供歷史'}]),send=h.connect('https://max411008.github.io/flight-price-board/');await send({type:'ping'});assert.equal(h.messages[0].version,2);await send({type:'refresh',jobs:[{...q,sourceUrl:'https://example.org/untrusted'}]});assert.equal(h.messages.find(m=>m.type==='result').result.current,34134);assert.equal(h.created[0].url,flightUrl(q));assert.deepEqual(h.removed,[1]);});
test('CAPTCHA stops remaining jobs; untrusted page cannot start updates',async()=>{const h=harness([{error:'Google 要求人工驗證'}]),send=h.connect('https://max411008.github.io/flight-price-board/');await send({type:'refresh',jobs:[q,q]});assert.equal(h.created.length,1);assert.match(h.messages.at(-1).message,/停止/);const other=harness([]);other.connect('https://max411008.github.io/unrelated/');assert.equal(other.messages[0].type,'disconnected');});
