"use client";
import { useEffect, useState, useCallback, useRef } from "react";
import { Plane, Plus, RefreshCw, ExternalLink, ChartNoAxesCombined, Puzzle, Archive } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import initial from "@/lib/seed.json";
import TripPrices from "@/components/trip-prices";
type Flight = Omit<typeof initial[number], 'current'> & {current:number|null;error?:string};
const money = (v: number | null) => v ? "NT$ " + v.toLocaleString("en-US") : "尚無資料";
export default function Board() {
 const [flights,setFlights]=useState<Flight[]>(initial),[selected,setSelected]=useState(initial[0].id),[adding,setAdding]=useState(false),[setup,setSetup]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[updating,setUpdating]=useState(false),[ready,setReady]=useState(false);
 const [form,setForm]=useState({flight:"",departure:"2026-10-23",origin:"TPE",destination:"MFM"});
 const ref=useRef(flights);ref.current=flights;
 const active=flights.find(f=>f.id===selected)||flights[0];
 const prices=active?.history.map(p=>p.price)||[],low=prices.length?Math.min(...prices):0,high=prices.length?Math.max(...prices):0;
 const load=useCallback(async()=>{const r=await fetch('/api/flights');if(!r.ok)throw Error('清單讀取失敗');const x=await r.json() as Flight[];setFlights(x);setReady(true);return x},[]);
 useEffect(()=>{void load().catch(()=>setNotice('目前顯示已查到的快照；儲存服務尚未連線。'))},[load]);
 useEffect(()=>{const handler=async(e:MessageEvent)=>{if(e.source!==window||e.origin!==location.origin||e.data?.source!=='fare-bridge')return;if(e.data.type==='ready'){setConnected(true)}if(e.data.type==='disconnected'){setConnected(false);setUpdating(false);setNotice('免費助手已斷線，請重新整理此頁。')}if(e.data.type==='progress')setNotice(e.data.message);if(e.data.type==='complete'){setUpdating(false);setNotice(e.data.message||'本次更新已結束。');}if(e.data.type==='result'){try{const r=await fetch('/api/flights/'+encodeURIComponent(e.data.id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(e.data.result)});if(!r.ok)throw Error('資料儲存失敗');await load();}catch{setNotice('已查詢，但資料儲存失敗，請稍後再試。')}}};window.addEventListener('message',handler);window.postMessage({source:'fare-board',type:'ping'},location.origin);return()=>window.removeEventListener('message',handler)},[load]);
 const refresh=useCallback((ids?:string[])=>{if(!connected){setSetup(true);return}const jobs=ref.current.filter(f=>!ids||ids.includes(f.id));setUpdating(true);setNotice('正在依序開啟 Google Flights 查詢，請保持此頁開啟。');window.postMessage({source:'fare-board',type:'refresh',jobs:jobs.map(({id,flight,departure,origin,destination,sourceUrl})=>({id,flight,departure,origin,destination,sourceUrl}))},location.origin)},[connected]);
 const create=useCallback(async(input:unknown)=>{const r=await fetch('/api/flights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const x=await r.json() as Flight & {error?:string};if(!r.ok)throw Error(x.error);await load();setSelected(x.id);return {id:x.id,flight:x.flight,departure:x.departure}},[load]);
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);try{await create(form);setAdding(false);setNotice('已加入清單。按更新價格取得來源目前提供的歷史。');}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{if(!connected||!ready)return;const run=()=>{const stale=ref.current.filter(f=>!f.observedAt||Date.now()-Date.parse(f.observedAt)>3600000);if(stale.length)refresh(stale.map(f=>f.id))};run();const timer=setInterval(run,3600000);return()=>clearInterval(timer)},[connected,ready,refresh]);
 useEffect(()=>{type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
 register({name:'list_flight_queries',description:'讀取航價簿目前保存的航班、價格、歷史與資料時間。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>ref.current});
 register({name:'add_flight_query',description:'新增並保存指定航班及起飛日期的查詢。尚無價格時保持空值。',inputSchema:{type:'object',properties:{flight:{type:'string'},departure:{type:'string'},origin:{type:'string'},destination:{type:'string'}},required:['flight','departure','origin','destination'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:create});
 register({name:'start_fare_refresh',description:'透過免費瀏覽器助手開始更新所有已保存航班；此動作回傳開始狀態，不代表已完成查詢。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!connected)throw Error('尚未連接瀏覽器助手');if(updating)throw Error('查詢執行中');refresh();return {status:'started'}}});return()=>lifecycle.abort()},[create,connected,updating,refresh]);
 async function archive(id:string){try{const r=await fetch('/api/flights/'+id,{method:'DELETE'});if(!r.ok)throw Error();await load();setNotice('已從清單移除；再次加入相同航班和日期可恢復已保存的資料。')}catch{setNotice('移除失敗，請重試。')}}
 return <div className="min-h-screen">
  <header className="bg-[#112943] text-white"><div className="mx-auto max-w-[1440px] flex flex-wrap gap-3 items-center justify-between px-5 md:px-10 py-5"><div className="flex gap-3 items-center"><Plane className="size-6 text-[#80b9ff]"/><span className="text-xl font-bold tracking-wide">航價簿</span><span className="text-sm border-l border-white/25 pl-4 ml-2 text-slate-300 hidden sm:inline">我的航班觀察清單</span></div><button onClick={()=>setSetup(true)} className="text-sm text-slate-200 flex gap-2 items-center"><Puzzle size={16}/>{connected?'免費更新助手已連線':'設定免費更新助手'}</button></div></header>
  <main className="max-w-[1440px] mx-auto px-5 md:px-10 py-8 space-y-6">
   <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-slate-500 mb-2">FLIGHT WATCHLIST</p><h1 className="text-3xl font-semibold tracking-tight">想飛的航班，一起看價格。</h1><p className="text-slate-500 mt-3">指定航班與出發日，比較已有的歷史記錄。</p></div><div className="flex gap-3"><Button variant="outline" size="lg" disabled={!ready||updating||!flights.length} onClick={()=>refresh()}><RefreshCw className={updating?'animate-spin':''}/>{updating?'查詢中…':'更新全部'}</Button><Button size="lg" disabled={!ready} onClick={()=>setAdding(true)}><Plus/>新增航班</Button></div></div>
   <div role="status" className="border-l-4 border-amber-500 bg-amber-50 text-amber-950 px-5 py-3 text-sm leading-6">{notice||'價格依各筆「資料時間」顯示，並非即時保證報價。安裝免費更新助手後可批次查詢；Google 未提供的歷史無法補齊。'}</div>
   <TripPrices flights={flights}/>
   <section className="bg-white border rounded-xl overflow-hidden"><div className="px-6 py-5 flex flex-wrap gap-3 justify-between items-center"><h2 className="text-lg font-semibold">追蹤中的航班 <span className="text-sm font-normal text-slate-500 ml-2">{flights.length} 筆查詢</span></h2><span className="text-sm text-slate-500">TWD · 單程 · 1 位成人 · 經濟艙</span></div><Table><TableHeader className="bg-slate-50"><TableRow><TableHead className="pl-6">航班 / 航線</TableHead><TableHead>出發日期</TableHead><TableHead>最近查到的價格</TableHead><TableHead>期間最低</TableHead><TableHead>較期間最低</TableHead><TableHead>資料時間</TableHead><TableHead>操作</TableHead></TableRow></TableHeader><TableBody>{flights.map(f=>{const min=f.history.length?Math.min(...f.history.map(p=>p.price)):0;return <TableRow key={f.id} data-state={active?.id===f.id?'selected':undefined} className="cursor-pointer" onClick={()=>setSelected(f.id)}><TableCell className="pl-6 py-5"><button className="font-semibold text-base text-blue-700" onClick={()=>setSelected(f.id)}>{f.flight}</button><div className="text-sm text-slate-500 mt-1">{f.origin} — {f.destination}</div></TableCell><TableCell className="text-base tabular-nums whitespace-nowrap">{f.departure}</TableCell><TableCell className="text-lg font-semibold tabular-nums whitespace-nowrap">{money(f.current)}</TableCell><TableCell className="text-base tabular-nums whitespace-nowrap">{money(min)}</TableCell><TableCell className="text-amber-700 tabular-nums">{min&&f.current?`${f.current>=min?'+':''}${((f.current/min-1)*100).toFixed(1)}%`:'—'}</TableCell><TableCell className="text-slate-500 whitespace-nowrap">{f.observedAt?new Date(f.observedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'尚未查詢'}<div className="text-xs mt-1 text-amber-700">{f.error?'更新未成功':f.observedAt?'已保存查詢結果':'等待資料'}</div></TableCell><TableCell className="pr-5"><div className="flex"><a href={f.sourceUrl} target="_blank" rel="noreferrer" aria-label={`開啟 ${f.flight} Google Flights`} onClick={e=>e.stopPropagation()} className="inline-flex p-2 text-slate-500 hover:text-blue-700"><ExternalLink size={17}/></a><button title="移出清單" aria-label={`移除 ${f.flight}`} className="p-2 text-slate-400 hover:text-slate-800" onClick={e=>{e.stopPropagation();void archive(f.id)}}><Archive size={17}/></button></div></TableCell></TableRow>})}</TableBody></Table>{!flights.length&&<p className="p-10 text-center text-slate-500">清單還沒有航班，新增一筆開始查詢。</p>}</section>
   {active&&<section className="bg-white border rounded-xl p-5 md:p-7"><div className="flex flex-wrap justify-between gap-5"><div><div className="text-sm text-slate-500 mb-2">價格記錄 / {active.departure}</div><h2 className="text-2xl font-semibold">{active.flight} <span className="font-normal text-slate-500 ml-2">{active.origin} — {active.destination}</span></h2></div><div className="flex flex-wrap gap-6 md:gap-10"><div><p className="text-sm text-slate-500 mb-2">期間最低</p><p className="text-xl font-semibold text-blue-700 tabular-nums">{money(low)}</p></div><div><p className="text-sm text-slate-500 mb-2">期間最高</p><p className="text-xl font-semibold tabular-nums">{money(high)}</p></div><div><p className="text-sm text-slate-500 mb-2">已取得記錄</p><p className="text-xl font-semibold tabular-nums">{prices.length} <span className="text-sm font-normal">天</span></p></div></div></div>
   {active.error&&<p className="mt-5 text-sm text-amber-800">{active.error} · 先前資料仍保留。</p>}
   <div className="h-[280px] mt-8">{prices.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={active.history} margin={{top:10,right:15,bottom:5,left:0}}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#e1e8f0"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5).replace('-','/')} tick={{fontSize:12,fill:'#65758a'}} minTickGap={35} axisLine={false} tickLine={false} dy={10}/><YAxis tickFormatter={v=>v.toLocaleString()} width={65} tick={{fontSize:12,fill:'#65758a'}} axisLine={false} tickLine={false} domain={['dataMin - 500','dataMax + 500']}/><Tooltip labelFormatter={v=>`觀察日 ${v}`} formatter={v=>[money(Number(v)),'單程價格']} contentStyle={{borderRadius:10,borderColor:'#dce4ef'}}/><Line type="stepAfter" dataKey="price" stroke="#2262d8" strokeWidth={2.5} dot={false} activeDot={{r:5}} connectNulls={false}/></LineChart></ResponsiveContainer>:<div className="h-full flex flex-col items-center justify-center gap-3 text-slate-500"><ChartNoAxesCombined className="size-10 text-slate-300"/><p>這筆航班還沒有取得歷史價格。</p><Button variant="outline" disabled={!ready||updating} onClick={()=>refresh([active.id])}>查詢這筆航班</Button></div>}</div><p className="text-xs text-slate-500 mt-5">橫軸是票價觀察日，並非起飛日期。以來源實際提供的歷史為準；售價依行李、票種與銷售平台而異。</p></section>}
   <footer className="text-sm text-slate-500 flex flex-wrap justify-between gap-4"><span>Google Flights 各通路最低售價 · 單程相加不代表來回票價</span><span>助手連線且本頁開啟時，每 60 分鐘更新</span></footer>
  </main>
  <Dialog open={adding} onOpenChange={setAdding}><DialogContent><DialogTitle>新增航班查詢</DialogTitle><DialogDescription>每個航班搭配一個出發日期，會存成獨立查詢。</DialogDescription><form onSubmit={add} className="space-y-5"><label className="block text-sm space-y-2"><span>航班編號</span><Input required placeholder="例如 JX201" value={form.flight} onChange={e=>setForm({...form,flight:e.target.value.toUpperCase()})}/></label><label className="block text-sm space-y-2"><span>出發日期</span><Input type="date" required value={form.departure} onChange={e=>setForm({...form,departure:e.target.value})}/></label><div className="grid grid-cols-2 gap-4"><label className="block text-sm space-y-2"><span>出發機場 IATA</span><Input required maxLength={3} value={form.origin} onChange={e=>setForm({...form,origin:e.target.value.toUpperCase()})}/></label><label className="block text-sm space-y-2"><span>抵達機場 IATA</span><Input required maxLength={3} value={form.destination} onChange={e=>setForm({...form,destination:e.target.value.toUpperCase()})}/></label></div><p className="text-sm text-slate-500">1 位成人、經濟艙、單程。新增不保證來源提供歷史。</p><Button disabled={busy} className="w-full" type="submit">{busy?'儲存中…':'加入清單'}</Button></form></DialogContent></Dialog>
  <Dialog open={setup} onOpenChange={setSetup}><DialogContent><DialogTitle>免費更新助手</DialogTitle><DialogDescription>透過你的 Chrome／Edge 讀取 Google Flights 的畫面資料，不使用付費 API。</DialogDescription><ol className="list-decimal pl-5 space-y-3 text-sm leading-6"><li><a className="text-blue-700 underline" href="/fare-bridge.zip" download>下載更新助手</a>，解壓縮到固定資料夾。</li><li>開啟 Chrome 或 Edge 的「擴充功能」管理頁，開啟「開發人員模式」，選擇「載入未封裝項目」並選取該資料夾。</li><li>用同一瀏覽器開啟本網頁並重新整理，再按「更新全部」。</li></ol><p className="text-sm text-slate-500">更新時會依序開啟航班頁面；請保持瀏覽器與本頁開啟。若 Google 要求驗證，助手會停止該筆查詢，需你自行處理。不會自動訂票或購買。</p><p className="text-sm text-blue-700">{connected?'助手已連線，可以更新。':'尚未偵測到助手。Codex 內嵌瀏覽器不支援安裝。'}</p></DialogContent></Dialog>
 </div>;
}
